/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedIssuesRouteImport } from './routes/_authenticated/issues'
import { Route as AuthenticatedMachinesRouteImport } from './routes/_authenticated/machines'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedPersonnelRouteImport } from './routes/_authenticated/personnel'
import { Route as AuthenticatedPlanningRouteImport } from './routes/_authenticated/planning'
<<<<<<< HEAD
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedQualityRouteImport } from './routes/_authenticated/quality'
import { Route as AuthenticatedWipRouteImport } from './routes/_authenticated/wip'
import { Route as AuthenticatedWorkOrdersRouteImport } from './routes/_authenticated/work-orders'
import { Route as AuthenticatedSubProductionManagementRouteImport } from './routes/_authenticated/sub/productionManagement'
import { Route as AuthenticatedSubQualityManagementRouteImport } from './routes/_authenticated/sub/qualityManagement'
=======
import { Route as AuthenticatedWipRouteImport } from './routes/_authenticated/wip'
import { Route as AuthenticatedWorkOrdersRouteImport } from './routes/_authenticated/work-orders'
>>>>>>> origin/View-Code-Ver2.8

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIssuesRoute = AuthenticatedIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMachinesRoute = AuthenticatedMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonnelRoute = AuthenticatedPersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanningRoute = AuthenticatedPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
<<<<<<< HEAD
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQualityRoute = AuthenticatedQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
=======
>>>>>>> origin/View-Code-Ver2.8
const AuthenticatedWipRoute = AuthenticatedWipRouteImport.update({
  id: '/wip',
  path: '/wip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkOrdersRoute = AuthenticatedWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
<<<<<<< HEAD
const AuthenticatedSubProductionManagementRoute =
  AuthenticatedSubProductionManagementRouteImport.update({
    id: '/sub/productionManagement',
    path: '/sub/productionManagement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubQualityManagementRoute =
  AuthenticatedSubQualityManagementRouteImport.update({
    id: '/sub/qualityManagement',
    path: '/sub/qualityManagement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
=======
>>>>>>> origin/View-Code-Ver2.8

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/issues': typeof AuthenticatedIssuesRoute
  '/machines': typeof AuthenticatedMachinesRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/personnel': typeof AuthenticatedPersonnelRoute
  '/planning': typeof AuthenticatedPlanningRoute
<<<<<<< HEAD
  '/production': typeof AuthenticatedProductionRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/wip': typeof AuthenticatedWipRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/sub/productionManagement': typeof AuthenticatedSubProductionManagementRoute
  '/sub/qualityManagement': typeof AuthenticatedSubQualityManagementRoute
=======
  '/wip': typeof AuthenticatedWipRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
>>>>>>> origin/View-Code-Ver2.8
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/issues': typeof AuthenticatedIssuesRoute
  '/machines': typeof AuthenticatedMachinesRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/personnel': typeof AuthenticatedPersonnelRoute
  '/planning': typeof AuthenticatedPlanningRoute
<<<<<<< HEAD
  '/production': typeof AuthenticatedProductionRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/wip': typeof AuthenticatedWipRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/': typeof AuthenticatedIndexRoute
  '/sub/productionManagement': typeof AuthenticatedSubProductionManagementRoute
  '/sub/qualityManagement': typeof AuthenticatedSubQualityManagementRoute
=======
  '/wip': typeof AuthenticatedWipRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/': typeof AuthenticatedIndexRoute
>>>>>>> origin/View-Code-Ver2.8
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/issues': typeof AuthenticatedIssuesRoute
  '/_authenticated/machines': typeof AuthenticatedMachinesRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRoute
  '/_authenticated/personnel': typeof AuthenticatedPersonnelRoute
  '/_authenticated/planning': typeof AuthenticatedPlanningRoute
<<<<<<< HEAD
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/quality': typeof AuthenticatedQualityRoute
  '/_authenticated/wip': typeof AuthenticatedWipRoute
  '/_authenticated/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/sub/productionManagement': typeof AuthenticatedSubProductionManagementRoute
  '/_authenticated/sub/qualityManagement': typeof AuthenticatedSubQualityManagementRoute
=======
  '/_authenticated/wip': typeof AuthenticatedWipRoute
  '/_authenticated/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
>>>>>>> origin/View-Code-Ver2.8
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/issues'
    | '/machines'
    | '/materials'
    | '/personnel'
    | '/planning'
<<<<<<< HEAD
    | '/production'
    | '/quality'
    | '/wip'
    | '/work-orders'
    | '/sub/productionManagement'
    | '/sub/qualityManagement'
=======
    | '/wip'
    | '/work-orders'
>>>>>>> origin/View-Code-Ver2.8
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/issues'
    | '/machines'
    | '/materials'
    | '/personnel'
    | '/planning'
<<<<<<< HEAD
    | '/production'
    | '/quality'
    | '/wip'
    | '/work-orders'
    | '/'
    | '/sub/productionManagement'
    | '/sub/qualityManagement'
=======
    | '/wip'
    | '/work-orders'
    | '/'
>>>>>>> origin/View-Code-Ver2.8
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/issues'
    | '/_authenticated/machines'
    | '/_authenticated/materials'
    | '/_authenticated/personnel'
    | '/_authenticated/planning'
<<<<<<< HEAD
    | '/_authenticated/production'
    | '/_authenticated/quality'
    | '/_authenticated/wip'
    | '/_authenticated/work-orders'
    | '/_authenticated/'
    | '/_authenticated/sub/productionManagement'
    | '/_authenticated/sub/qualityManagement'
=======
    | '/_authenticated/wip'
    | '/_authenticated/work-orders'
    | '/_authenticated/'
>>>>>>> origin/View-Code-Ver2.8
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/issues': {
      id: '/_authenticated/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof AuthenticatedIssuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/machines': {
      id: '/_authenticated/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof AuthenticatedMachinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personnel': {
      id: '/_authenticated/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof AuthenticatedPersonnelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planning': {
      id: '/_authenticated/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AuthenticatedPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
<<<<<<< HEAD
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quality': {
      id: '/_authenticated/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AuthenticatedQualityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
=======
>>>>>>> origin/View-Code-Ver2.8
    '/_authenticated/wip': {
      id: '/_authenticated/wip'
      path: '/wip'
      fullPath: '/wip'
      preLoaderRoute: typeof AuthenticatedWipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-orders': {
      id: '/_authenticated/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof AuthenticatedWorkOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
<<<<<<< HEAD
    '/_authenticated/sub/productionManagement': {
      id: '/_authenticated/sub/productionManagement'
      path: '/sub/productionManagement'
      fullPath: '/sub/productionManagement'
      preLoaderRoute: typeof AuthenticatedSubProductionManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sub/qualityManagement': {
      id: '/_authenticated/sub/qualityManagement'
      path: '/sub/qualityManagement'
      fullPath: '/sub/qualityManagement'
      preLoaderRoute: typeof AuthenticatedSubQualityManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
=======
>>>>>>> origin/View-Code-Ver2.8
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIssuesRoute: typeof AuthenticatedIssuesRoute
  AuthenticatedMachinesRoute: typeof AuthenticatedMachinesRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRoute
  AuthenticatedPersonnelRoute: typeof AuthenticatedPersonnelRoute
  AuthenticatedPlanningRoute: typeof AuthenticatedPlanningRoute
<<<<<<< HEAD
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedQualityRoute: typeof AuthenticatedQualityRoute
  AuthenticatedWipRoute: typeof AuthenticatedWipRoute
  AuthenticatedWorkOrdersRoute: typeof AuthenticatedWorkOrdersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSubProductionManagementRoute: typeof AuthenticatedSubProductionManagementRoute
  AuthenticatedSubQualityManagementRoute: typeof AuthenticatedSubQualityManagementRoute
=======
  AuthenticatedWipRoute: typeof AuthenticatedWipRoute
  AuthenticatedWorkOrdersRoute: typeof AuthenticatedWorkOrdersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
>>>>>>> origin/View-Code-Ver2.8
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIssuesRoute: AuthenticatedIssuesRoute,
  AuthenticatedMachinesRoute: AuthenticatedMachinesRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRoute,
  AuthenticatedPersonnelRoute: AuthenticatedPersonnelRoute,
  AuthenticatedPlanningRoute: AuthenticatedPlanningRoute,
<<<<<<< HEAD
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedQualityRoute: AuthenticatedQualityRoute,
  AuthenticatedWipRoute: AuthenticatedWipRoute,
  AuthenticatedWorkOrdersRoute: AuthenticatedWorkOrdersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSubProductionManagementRoute:
    AuthenticatedSubProductionManagementRoute,
  AuthenticatedSubQualityManagementRoute:
    AuthenticatedSubQualityManagementRoute,
=======
  AuthenticatedWipRoute: AuthenticatedWipRoute,
  AuthenticatedWorkOrdersRoute: AuthenticatedWorkOrdersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
>>>>>>> origin/View-Code-Ver2.8
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
