/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedIssuesRouteImport } from './routes/_authenticated/issues'
import { Route as AuthenticatedMachinesRouteImport } from './routes/_authenticated/machines'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedPersonnelRouteImport } from './routes/_authenticated/personnel'
import { Route as AuthenticatedPlanningRouteImport } from './routes/_authenticated/planning'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedQualityRouteImport } from './routes/_authenticated/quality'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedWarehouseRouteImport } from './routes/_authenticated/warehouse'
import { Route as AuthenticatedWipRouteImport } from './routes/_authenticated/wip'
import { Route as AuthenticatedWorkOrdersRouteImport } from './routes/_authenticated/work-orders'
import { Route as AuthenticatedSubProductionManagementRouteImport } from './routes/_authenticated/sub/productionManagement'
import { Route as AuthenticatedSubQualityManagementRouteImport } from './routes/_authenticated/sub/qualityManagement'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIssuesRoute = AuthenticatedIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMachinesRoute = AuthenticatedMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonnelRoute = AuthenticatedPersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanningRoute = AuthenticatedPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQualityRoute = AuthenticatedQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWarehouseRoute = AuthenticatedWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWipRoute = AuthenticatedWipRouteImport.update({
  id: '/wip',
  path: '/wip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkOrdersRoute = AuthenticatedWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubProductionManagementRoute =
  AuthenticatedSubProductionManagementRouteImport.update({
    id: '/sub/productionManagement',
    path: '/sub/productionManagement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubQualityManagementRoute =
  AuthenticatedSubQualityManagementRouteImport.update({
    id: '/sub/qualityManagement',
    path: '/sub/qualityManagement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/issues': typeof AuthenticatedIssuesRoute
  '/machines': typeof AuthenticatedMachinesRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/personnel': typeof AuthenticatedPersonnelRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouse': typeof AuthenticatedWarehouseRoute
  '/wip': typeof AuthenticatedWipRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/sub/productionManagement': typeof AuthenticatedSubProductionManagementRoute
  '/sub/qualityManagement': typeof AuthenticatedSubQualityManagementRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/issues': typeof AuthenticatedIssuesRoute
  '/machines': typeof AuthenticatedMachinesRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/personnel': typeof AuthenticatedPersonnelRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouse': typeof AuthenticatedWarehouseRoute
  '/wip': typeof AuthenticatedWipRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/': typeof AuthenticatedIndexRoute
  '/sub/productionManagement': typeof AuthenticatedSubProductionManagementRoute
  '/sub/qualityManagement': typeof AuthenticatedSubQualityManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/issues': typeof AuthenticatedIssuesRoute
  '/_authenticated/machines': typeof AuthenticatedMachinesRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRoute
  '/_authenticated/personnel': typeof AuthenticatedPersonnelRoute
  '/_authenticated/planning': typeof AuthenticatedPlanningRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/quality': typeof AuthenticatedQualityRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/warehouse': typeof AuthenticatedWarehouseRoute
  '/_authenticated/wip': typeof AuthenticatedWipRoute
  '/_authenticated/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/sub/productionManagement': typeof AuthenticatedSubProductionManagementRoute
  '/_authenticated/sub/qualityManagement': typeof AuthenticatedSubQualityManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/issues'
    | '/machines'
    | '/maintenance'
    | '/materials'
    | '/personnel'
    | '/planning'
    | '/production'
    | '/products'
    | '/quality'
    | '/tasks'
    | '/users'
    | '/warehouse'
    | '/wip'
    | '/work-orders'
    | '/sub/productionManagement'
    | '/sub/qualityManagement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/issues'
    | '/machines'
    | '/maintenance'
    | '/materials'
    | '/personnel'
    | '/planning'
    | '/production'
    | '/products'
    | '/quality'
    | '/tasks'
    | '/users'
    | '/warehouse'
    | '/wip'
    | '/work-orders'
    | '/'
    | '/sub/productionManagement'
    | '/sub/qualityManagement'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/issues'
    | '/_authenticated/machines'
    | '/_authenticated/maintenance'
    | '/_authenticated/materials'
    | '/_authenticated/personnel'
    | '/_authenticated/planning'
    | '/_authenticated/production'
    | '/_authenticated/products'
    | '/_authenticated/quality'
    | '/_authenticated/tasks'
    | '/_authenticated/users'
    | '/_authenticated/warehouse'
    | '/_authenticated/wip'
    | '/_authenticated/work-orders'
    | '/_authenticated/'
    | '/_authenticated/sub/productionManagement'
    | '/_authenticated/sub/qualityManagement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/issues': {
      id: '/_authenticated/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof AuthenticatedIssuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/machines': {
      id: '/_authenticated/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof AuthenticatedMachinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personnel': {
      id: '/_authenticated/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof AuthenticatedPersonnelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planning': {
      id: '/_authenticated/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AuthenticatedPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quality': {
      id: '/_authenticated/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AuthenticatedQualityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warehouse': {
      id: '/_authenticated/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof AuthenticatedWarehouseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wip': {
      id: '/_authenticated/wip'
      path: '/wip'
      fullPath: '/wip'
      preLoaderRoute: typeof AuthenticatedWipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-orders': {
      id: '/_authenticated/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof AuthenticatedWorkOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sub/productionManagement': {
      id: '/_authenticated/sub/productionManagement'
      path: '/sub/productionManagement'
      fullPath: '/sub/productionManagement'
      preLoaderRoute: typeof AuthenticatedSubProductionManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sub/qualityManagement': {
      id: '/_authenticated/sub/qualityManagement'
      path: '/sub/qualityManagement'
      fullPath: '/sub/qualityManagement'
      preLoaderRoute: typeof AuthenticatedSubQualityManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIssuesRoute: typeof AuthenticatedIssuesRoute
  AuthenticatedMachinesRoute: typeof AuthenticatedMachinesRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRoute
  AuthenticatedPersonnelRoute: typeof AuthenticatedPersonnelRoute
  AuthenticatedPlanningRoute: typeof AuthenticatedPlanningRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedQualityRoute: typeof AuthenticatedQualityRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWarehouseRoute: typeof AuthenticatedWarehouseRoute
  AuthenticatedWipRoute: typeof AuthenticatedWipRoute
  AuthenticatedWorkOrdersRoute: typeof AuthenticatedWorkOrdersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSubProductionManagementRoute: typeof AuthenticatedSubProductionManagementRoute
  AuthenticatedSubQualityManagementRoute: typeof AuthenticatedSubQualityManagementRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIssuesRoute: AuthenticatedIssuesRoute,
  AuthenticatedMachinesRoute: AuthenticatedMachinesRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRoute,
  AuthenticatedPersonnelRoute: AuthenticatedPersonnelRoute,
  AuthenticatedPlanningRoute: AuthenticatedPlanningRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedQualityRoute: AuthenticatedQualityRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWarehouseRoute: AuthenticatedWarehouseRoute,
  AuthenticatedWipRoute: AuthenticatedWipRoute,
  AuthenticatedWorkOrdersRoute: AuthenticatedWorkOrdersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSubProductionManagementRoute:
    AuthenticatedSubProductionManagementRoute,
  AuthenticatedSubQualityManagementRoute:
    AuthenticatedSubQualityManagementRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
